import { chromium, canvasShot, hookErrors, FILE } from "./judge-common.mjs"
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 800, height: 800 } })
const errors = []; hookErrors(page, errors)
await page.goto(FILE + "?seed=9")
await page.waitForTimeout(500)
await page.evaluate(() => { const d = BP.Game.debug; d.startAt(0, 0, 0); d.autoplay = 0.97; d.setCups(1, 1); for (let i = 0; i < 6000 && d.state !== 'clear'; i++) d.step(1); d.autoplay = false; d.step(260); d.render() })
await canvasShot(page, "clear-tally")
await page.evaluate(() => { const d = BP.Game.debug; d.startAt(0, 0, 0); d.autoplay = false; d.go('gameover'); d.step(200); d.render() })
await canvasShot(page, "gameover")
console.log(errors)
await browser.close()
